version: "3"

services:
  undefined:
    container_name: undefined
    depends_on: [db, redis]
    build: .
    ports:
      - "3000:3000/tcp"
    environment:
      HTTP_PORT: "3000"
      NODE_ENV: "development"
      RDS_HOST: "db"
      RDS_PORT: "3306"
      RDS_USERNAME: "root"
      RDS_PASSWORD: "localPassword"
      RDS_DATABASE: "undefined"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    restart: unless-stopped

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306/tcp"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: localPassword
      MYSQL_DATABASE: undefined

  redis:
    image: "redis:alpine"
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
        - "6379:6379/tcp"
    restart: unless-stopped
