version: '3'

services:
  mingrammer:
    image: pedromol/mingrammer
    working_dir: /usr/app
    command: find . -name "*.py" -exec python {} \;
    volumes:
      - ./:/usr/app

  seqdiag:
    image: pedromol/seqdiag
    working_dir: /usr/app
    command: find . -name "*.seqdiag" -exec node index.js {} +
    volumes:
      - ./:/usr/app/src

  # Disabled by issue : https://github.com/docker/compose/issues/8154
  # Using build.sh for now
  # bundler:
  #   image: debian:buster
  #   depends_on:
  #     mingrammer:
  #       condition: service_completed_successfully
  #     seqdiag:
  #       condition: service_completed_successfully
  #   working_dir: /usr/app
  #   command: bash -c "
  #     rm -Rf dist
  #     && cp -Rf src dist
  #     && find dist -type f ! -name "*.png" -delete
  #     "
  #   volumes:
  #     - ./:/usr/app
